all:
  children:
    main:
      hosts:
        pgxn.org:
          ansible_user: pgxn
    manager:
      hosts:
        manager.pgxn.org:
          ansible_user: pgxn_manager
    master:
      hosts:
        master.pgxn.org:
          ansible_user: pgxn_manager
    rsync:
      hosts:
        master.pgxn.org:
          ansible_user: pgxn_rsync
    api:
      hosts:
        api.pgxn.org:
          ansible_user: pgxn_api
    site:
      hosts:
        www.pgxn.org:
          ansible_user: pgxn_site
