---
- name: Build and Deploy PGXN Manager
  hosts: main
  tags: [deploy]
  tasks:
    - name: Include Variables
      include_vars:
        file: vars.yml
        name: app
    - name: Install Control Scripts
      template:
        src: "{{ item }}.j2"
        dest: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}/bin/{{ item }}"
        owner: pgxn
        group: pgxn
        mode: "u=rwx,g=rx,o="
      loop: [mgr_ctl, mgr_mirrors]
    - name: Configure {{ app.dist_name }}-{{ app.version }}
      template:
        # Password stored in 1Password as “PGXN Manager Secrets”
        src: prod.json.j2
        dest: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}/conf/prod.json"
        owner: pgxn
        group: pgxn
        mode: "u=rw,g=r,o="
    - name: Deploy {{ app.name }}-{{ app.version }}
      file:
        state: link
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        force: yes
      loop:
        - src: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}"
          dst: "{{ app.release_dir }}/{{ app.name }}"
        - src: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}"
          dst: "{{ app.deploy_dir }}"

- name: Restart PGXN Manager
  hosts: manager
  tags: [deploy]
  tasks:
    - name: Include Variables
      include_vars:
        file: vars.yml
        name: app
    - name: Link from {{ app.home_dir }}
      file:
        state: link
        src: "{{ app.deploy_dir }}"
        dest: "{{ app.home_dir }}/{{ app.name }}"
        force: yes
    - name: Setup Cron Environment
      cronvar:
        name: MAILTO
        value: "{{ app.opt.errors_to }}"
    - name: Deploy Mirror Sync Cron Job
      cron:
        name: Run PGXN Mirror Checker
        special_time: daily
        job: "{{ app.deploy_dir }}/bin/mgr_mirrors"
    - name: Create Service Directory
      file:
        path: "{{ app.home_dir }}/.config/systemd/user"
        state: directory
        mode: "0755"
    - name: Deploy Service Files
      loop: [manager, consumer]
      template:
        src: "{{ item }}.service"
        dest: "{{ app.home_dir }}/.config/systemd/user/{{ item }}.pgxn.org.service"
        mode: "0644"
    - name: Enable Linger for {{ ansible_user }}
      changed_when: false
      command:
        argv: [loginctl, enable-linger, "{{ ansible_user }}"]
    - name: Restart Manager
      loop: [manager, consumer]
      ansible.builtin.systemd_service:
        name: "{{ item }}.pgxn.org"
        scope: user
        enabled: true
        state: restarted
        daemon_reload: true
