---
- name: Restart PGXN Manager
  hosts: manager
  tags: [service]
  tasks:
    - name: Include Variables
      include_vars: file=vars.yml name=app
    - name: Restart PGXN Manager
      command:
        cmd: "{{ app.deploy_dir }}/bin/mgr_ctl restart"
