---
- name: Restart PGXN Manager
  hosts: manager
  tags: [service]
  tasks:
    - name: Restart Manager
      loop: [manager, consumer]
      ansible.builtin.systemd_service:
        name: "{{ item }}.pgxn.org"
        scope: user
        enabled: true
        state: restarted
        daemon_reload: true
