---
- name: Deploy PGXN Site
  hosts: main
  tags: [deploy]
  tasks:
    - name: Include Variables
      include_vars:
        file: vars.yml
        name: app
    - name: Install Control Script
      template:
        src: "site_ctl.j2"
        dest: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}/bin/site_ctl"
        owner: pgxn
        group: pgxn
        mode: "u=rwx,g=rx,o="
    - name: Deploy {{ app.name }}-{{ app.version }}
      file:
        state: link
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        force: true
      loop:
        - src: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}"
          dst: "{{ app.release_dir }}/{{ app.name }}"
        - src: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}"
          dst: "{{ app.deploy_dir }}"

- name: Restart PGXN
  hosts: site
  tags: [deploy]
  tasks:
    - name: Include Variables
      include_vars:
        file: vars.yml
        name: app
    - name: Link from {{ app.home_dir }}
      file:
        state: link
        src: "{{ app.deploy_dir }}"
        dest: "{{ app.home_dir }}/{{ app.name }}"
        force: true
    - name: Create Service Directory
      file:
        path: "{{ app.home_dir }}/.config/systemd/user"
        state: directory
        mode: "0755"
    - name: Deploy Service File
      template:
        mode: "0644"
        src: site.service
        dest: ~/.config/systemd/user/site.pgxn.org.service
    - name: Enable Linger for {{ ansible_user }}
      changed_when: false
      command:
        argv: [loginctl, enable-linger, "{{ ansible_user }}"]
    - name: Restart Site
      ansible.builtin.systemd_service:
        name: site.pgxn.org
        scope: user
        enabled: true
        state: restarted
        daemon_reload: true
