---
- name: Restart PGXN Site
  hosts: site
  tags: [service]
  tasks:
    - name: Restart Site
      ansible.builtin.systemd_service:
        name: site.pgxn.org
        scope: user
        state: restarted
        enabled: true
        daemon_reload: true
