---
- name: Build PGXN API
  hosts: main
  tags: [build]
  tasks:
    - name: Include Variables
      include_vars: file=vars.yml name=app
    - name: Create Directories
      file: path="{{ item }}" state=directory mode=u=rwx,g=rwx,o=
      loop:
        - "{{ app.release_dir }}"
        - "{{ app.release_dir }}/api-root"
        - "{{ app.release_dir }}/logs"
        - "{{ app.release_dir }}/pids"
        - "{{ app.deploy_dir }}"
    - name: Build {{ app.name }}-{{ app.version }}
      command:
        chdir: "{{ app.release_dir }}"
        creates: "{{ app.name }}-{{ app.version }}"
        cmd: cpanm --with-recommends --notest --local-lib-contained {{ app.name }}-{{ app.version }} {{ app.module }}@{{ app.version }} Cookie::Baker::XS WWW::Form::UrlEncoded::XS
    - name: Link {{ app.name }}-{{ app.version }}
      file:
        state: link
        src: "{{ app.release_dir }}/{{ item.src }}"
        dest: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}/{{ item.dst }}"
        force: yes
      loop:
        - { src: "logs", dst: logs }
        - { src: "pids", dst: pids }
        - { src: "api-root", dst: www }
