---
- name: Build PGXN API
  hosts: main
  tags: [build]
  tasks:
    - name: Include Variables
      include_vars: file=vars.yml name=app
    - name: Create Directories
      file: path="{{ item }}" state=directory
      loop:
        - "{{ app.release_dir }}"
        - "{{ app.release_dir }}/api-root"
        - "{{ app.release_dir }}/logs"
        - "{{ app.release_dir }}/pids"
        - "{{ app.release_dir }}/bin"
        - "{{ app.deploy_dir }}"
    - name: Build {{ app.name }}-{{ app.version }}
      command:
        chdir: "{{ app.release_dir }}"
        creates: "{{ app.name }}-{{ app.version }}"
        cmd: cpanm --with-recommends --notest --local-lib-contained {{ app.name }}-{{ app.version }} {{ app.module }}@{{ app.version }} Cookie::Baker::XS WWW::Form::UrlEncoded::XS
    - name: Link {{ app.name }}-{{ app.version }}
      file:
        state: link
        src: "{{ item.src }}"
        dest: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}/{{ item.dst }}"
        force: yes
      loop:
        - { src: "{{ app.release_dir }}/logs", dst: logs }
        - { src: "{{ app.release_dir }}/pids", dst: pids }
        - { src: "{{ app.release_dir }}/api-root", dst: www }

    # - name: Deploy {{ app.name }}-{{ app.version }}
    #   file:
    #     state: link
    #     src: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}"
    #     dest: "{{ app.deploy_dir }}/{{ app.app }}"
    #     force: yes
