---
- name: Deploy PGXN API
  hosts: main
  tags: [deploy]
  tasks:
    - name: Include Variables
      include_vars: file=vars.yml name=app
    - name: Install Control Scripts
      template:
        src: "{{ item }}.j2"
        dest: "{{ app.release_dir }}/bin/{{ item }}"
        owner: pgxn
        group: pgxn
        mode: "u=rwx,g=rx,o="
      loop: [api_ctl, api_sync]
    - name: Setup PGXN Cron Environment
      cronvar: name=MAILTO value={{ app.opt.errors_to }}
    - name: Deploy PGXN Cron Job
      cron:
        name: Doc root sync job
        minute: "*/5"
        job: "{{ app.release_dir }}/bin/api_sync"
    - name: Deploy {{ app.name }}-{{ app.version }}
      file:
        state: link
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        force: yes
      loop:
        - src: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}"
          dst: "{{ app.release_dir }}/{{ app.name }}"
        - src: "{{ app.release_dir }}/bin/api_ctl"
          dst: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}/bin/api_ctl"
        - src: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}"
          dst: "{{ app.deploy_dir }}"

- name: Restart PGXN
  hosts: api
  tags: [deploy]
  tasks:
    - name: Include Variables
      include_vars: file=vars.yml name=app
    - name: Setup API Cron Environment
      cronvar: name=MAILTO value={{ app.opt.errors_to }}
    - name: Deploy API Cron Job
      cron:
        name: Run PGXN API
        special_time: reboot
        job: "{{ app.deploy_dir }}/bin/api_ctl start"
    - name: Restart PGXN API
      command:
        cmd: "{{ app.deploy_dir }}/bin/api_ctl restart"
