---

- name: Build and Deploy PGXN API
  hosts: main
  vars:
    app: pgxn-api
    version: v0.16.5
    module: PGXN::API
    package: "{{ app }}-{{ version }}"
    work_dir: /home/{{ ansible_user }}/work
    release_dir: /home/{{ ansible_user }}/releases
    deploy_dir: /var/virtuals/pgxn
  tasks:
    - name: Create Work Directory
      file:
        path: "{{ work_dir }}"
        state: directory
    - name: Build {{ package }}
      command:
        chdir: "{{ work_dir }}"
        cmd: cpanm --with-recommends --notest --local-lib-contained {{ package }} {{ module }}@{{ version }} Cookie::Baker::XS WWW::Form::UrlEncoded::XS
    - name: Create Release Directory
      file:
        path: "{{ release_dir }}"
        state: directory
    - name: Install {{ package }}
      command:
        cmd: mv {{ work_dir }}/{{ package }} {{ release_dir }}
    - name: Release {{ package }}
      file:
        state: link
        src: "{{ work_dir }}/{{ package }}"
        dest: "{{ release_dir }}/app"
        force: yes
    - name: Create Deploy Directory
      file:
        path: "{{ deploy_dir }}"
        state: directory
    # - name: Deploy {{ package }}
    #   file:
    #     state: link
    #     src: "{{ release_dir }}/{{ package }}"
    #     dest: "{{ deploy_dir }}/{{ app }}"
    #     force: yes

- name: Restart PGXN API

