---
- name: Deploy PGXN API
  hosts: main
  tags: [deploy]
  tasks:
    - name: Include Variables
      ansible.builtin.include_vars:
        file: vars.yml
        name: app
    - name: Install Control Scripts
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}/bin/{{ item }}"
        owner: pgxn
        group: pgxn
        mode: "u=rwx,g=rx,o="
      loop: [api_sync]
    - name: Setup Cron Environment
      ansible.builtin.cron:
        env: true
        name: MAILTO
        value: "{{ app.opt.errors_to }}"
    - name: Deploy API Sync Cron Job
      ansible.builtin.cron:
        name: Doc root sync job
        minute: "*/5"
        job: "{{ app.deploy_dir }}/bin/api_sync"
    - name: Deploy {{ [app.name, app.version] | join('-') }}
      ansible.builtin.file:
        state: link
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        force: true
      loop:
        - src: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}"
          dst: "{{ app.release_dir }}/{{ app.name }}"
        - src: "{{ app.release_dir }}/{{ app.name }}-{{ app.version }}"
          dst: "{{ app.deploy_dir }}"

- name: Restart PGXN API
  hosts: api
  tags: [deploy]
  tasks:
    - name: Include Variables
      ansible.builtin.include_vars:
        file: vars.yml
        name: app
    - name: Link from {{ app.home_dir }}
      ansible.builtin.file:
        state: link
        src: "{{ app.deploy_dir }}"
        dest: "{{ app.home_dir }}/{{ app.name }}"
        force: true
    - name: Create Service Directory
      ansible.builtin.file:
        path: "{{ app.home_dir }}/.config/systemd/user"
        state: directory
        mode: "u=rwx,go=rx"
    - name: Deploy Service File
      ansible.builtin.template:
        src: api.service
        dest: "{{ app.home_dir }}/.config/systemd/user/api.pgxn.org.service"
        mode: "u=rw,g=r,o="
    - name: Enable Linger for {{ ansible_user }}
      changed_when: false
      ansible.builtin.command:
        argv: [loginctl, enable-linger, "{{ ansible_user }}"]
    - name: Enable & Restart
      ansible.builtin.systemd_service:
        name: api.pgxn.org
        scope: user
        enabled: true
        state: restarted
        daemon_reload: true
