---
- name: Restart PGXN API
  hosts: api
  tags: [service]
  tasks:
    - name: Restart API Service
      ansible.builtin.systemd_service:
        name: api.pgxn.org
        scope: user
        enabled: true
        state: restarted
        daemon_reload: true
