---
- name: Restart PGXN API
  hosts: api
  tags: [service]
  tasks:
    - name: Include Variables
      include_vars: file=vars.yml name=app
    - command:
        cmd: "{{ app.deploy_dir }}/bin/api_ctl restart"
